### PR TITLE
[#1480] MQTT-Adapter: fix wrong topic for commands sent to gateway; add documentation

### LINKED ISSUE #1480: MQTT-Adapter: fix wrong topic for commands sent to gateway; add documentation
With #930 support has been added for command messages to be redirected to the current gateway that the target device is connected to.

In the case of the MQTT adapter, this means:
- an authenticated gateway will subscribe for commands (not for a particular device but for all devices using that gateway),
- a northbound application will send a command to a particular device (not knowing its gateway id),
- the protocol adapter will determine the last known gateway for that device and publish the command to it.

What is missing here is that the topic used when publishing the command to the gateway doesn't contain the original device id. The topic currently looks just like this: `command///req/xyz/light`. Instead, the device id should be set in there (e.g. `command//4712/req/xyz/light`) so that the gateway can properly handle the command.

Also, documenation for that scenario is missing still.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #1480.

### CODE REVIEW

File: client/src/main/java/org/eclipse/hono/client/Command.java [hunk 1]
```diff
@@ -246,6 +250,47 @@ public String getDeviceId() {
...
+        if (isValid()) {
+            final String originalDeviceId = getOriginalDeviceId();
+            return originalDeviceId != null && !originalDeviceId.equals(getDeviceId());
+        } else {
+            throw new IllegalStateException("command is invalid");
+        }
+    }
+
+    /**
+     * Gets the device identifier used in the original command.
```
Comment (sophokles73) [inline client/src/main/java/org/eclipse/hono/client/Command.java]: IMHO the comment should explicitly explain that the value returned is extracted from the AMQP message's *to* property.

File: client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java [hunk 2]
```diff
@@ -201,14 +197,10 @@ static String getTargetAddress(final String tenantId, final String deviceId) {
...
 
-    private static Message createDelegatedCommandMessage(final Message originalMessage, final String targetAddress,
-            final String replyToAddress) {
-        Objects.requireNonNull(targetAddress);
+    private static Message createDelegatedCommandMessage(final Message originalMessage, final String replyToAddress) {
         Objects.requireNonNull(originalMessage);
         // copy original message
         final Message msg = MessageHelper.getShallowCopy(originalMessage);
-        // set target address
-        msg.setAddress(targetAddress);
```
Comment (sophokles73) [inline client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java]: why is this no longer necessary?

File: site/documentation/content/concepts/command-and-control.md [hunk 3]
```diff
@@ -59,11 +59,21 @@ and *one-way* commands on the topic:
...
-while unauthenticated devices have to fully specify their `${tenant}` and `${device-id}` during the subscription.
+while unauthenticated devices have to fully specify their `${tenant}` and `${device-id}` in the subscription topic:
+
+* `command/${tenant-id}/${device-id}/req/#`
+
+Authenticated gateways subscribe to
+
+* `command/+/+/req/#`
+
+and will receive commands on a topic where the target device id is set.
```
Comment (sophokles73) [inline site/documentation/content/concepts/command-and-control.md]: and will receive commands on a topic that contains the target device id.

File: site/documentation/content/user-guide/mqtt-adapter.md [hunk 4]
```diff
@@ -259,6 +259,27 @@ and *one-way* commands to the topic:
...
+
+If a device is configured in such a way that there can be *one* gateway, acting on behalf of the device, a command sent to this device will by default be directed to that gateway.
+
+If a device is configured to be used with *multiple* gateways, the particular gateway that last acted on behalf of the device will be the target that commands for that device will be routed to. The mapping of device and gateway last used by the device is updated whenever a device sends a telemetry, event or command response message via the gateway. This means that for a device configured to be used via multiple gateways to receive commands, the device first has to send at least one telemetry or event message to establish which gateway to use for receiving commands for that device.
+
+An authenticated gateway MUST use the following topic filter to subscribe to commands:
```
Comment (sophokles73) [inline site/documentation/content/user-guide/mqtt-adapter.md]: ... to commands for all the devices it acts on behalf of:

File: site/documentation/content/user-guide/mqtt-adapter.md [hunk 5]
```diff
@@ -259,6 +259,27 @@ and *one-way* commands to the topic:
...
+* `command/+/+/req/#`
+
+**Example**
+
+    mosquitto_sub -v -u 'gw@DEFAULT_TENANT' -P gw-secret -t command/+/+/req/#
+
+The adapter will then publish commands for devices, that the gateway has acted on behalf of, to topic:
+
+* for *Request/Response* commands: `command//${device-id}/req/${req-id}/${command}[/*][/property-bag]`
+* for *one-way* commands: `command//${device-id}/req//${command}[/*][/property-bag]`
```
Comment (sophokles73) [inline site/documentation/content/user-guide/mqtt-adapter.md]: the topic we send commands to cannot contain a property bag, can it?

File: client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java (hunk 2 above)
Comment (calohmn) [reply client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java]: It was only necessary because we used an anonymous relay link here. But with #1474 this has been changed. We use a non-empty link address now and therefore we don't need to explicitly set the message address.

The address of the original command message is supposed to be preserved here. This is relevant for the case that the message is to be delegated to a gateway.

File: site/documentation/content/user-guide/mqtt-adapter.md (hunk 5 above)
Comment (calohmn) [reply site/documentation/content/user-guide/mqtt-adapter.md]: Right, I've removed the `[/*][/property-bag]` part also in the other places on the page.

**Comment by calohmn** [comment]
@sophokles73 I've made the corresponding changes.

File: client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java (hunk 2 above)
Comment (sophokles73) [reply client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java]: > The address of the original command message is supposed to be preserved here. 

it will be copied by the *getShallowCopy* method?

Comment (calohmn) [reply client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java]: yes (along with the other message properties).
