### PR TITLE
[#3312] Remove timeout on initial subscribeAndWaitForRebalance()

### LINKED ISSUE #3312: Hono components using Kafka consumer may fail to reach ready state
Hono components that create a Kafka consumer during startup may fail to reach the ready state in cases where the Kafka broker is restarted immediately after the Hono component has created the Kafka consumer.

This has occurred sporadically while running the Hono Helm chart's CI process during which Hono is installed to different versions of k8s.
The log file of a protocol adapter in this case contains:
```sh
2022-06-22 13:53:47,121 WARN  [org.apa.kaf.cli.ClientUtils] (vert.x-eventloop-thread-1) Couldn't resolve server hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless:9092 from bootstrap.servers as DNS resolution failed for hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless
2022-06-22 13:53:47,121 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) error creating Kafka client, will retry in 1000ms: No resolvable bootstrap urls given in bootstrap.servers
2022-06-22 13:53:47,121 WARN  [org.apa.kaf.cli.ClientUtils] (vert.x-eventloop-thread-1) Couldn't resolve server hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless:9092 from bootstrap.servers as DNS resolution failed for hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless
2022-06-22 13:53:47,121 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) error creating Kafka client, will retry in 1000ms: No resolvable bootstrap urls given in bootstrap.servers
2022-06-22 13:53:47,976 INFO  [org.apa.kaf.com.sec.aut.AbstractLogin] (vert.x-eventloop-thread-0) Successfully logged in.
2022-06-22 13:53:48,421 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-0) successfully created client [type: io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl]
2022-06-22 13:53:48,474 DEBUG [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (vert.x-eventloop-thread-1) registered producer (1 producers total)
2022-06-22 13:53:48,474 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: io.vertx.kafka.client.producer.impl.KafkaProducerImpl]
2022-06-22 13:53:48,490 DEBUG [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (vert.x-eventloop-thread-1) registered producer (2 producers total)
2022-06-22 13:53:48,490 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: io.vertx.kafka.client.producer.impl.KafkaProducerImpl]
2022-06-22 13:53:48,513 DEBUG [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (vert.x-eventloop-thread-1) registered producer (3 producers total)
2022-06-22 13:53:48,513 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: io.vertx.kafka.client.producer.impl.KafkaProducerImpl]
2022-06-22 13:53:48,531 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: org.apache.kafka.clients.admin.KafkaAdminClient]
...

2022-06-22 13:53:48,733 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-admin-client-thread | internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0) [AdminClient clientId=internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.
2022-06-22 13:53:48,837 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-admin-client-thread | internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0) [AdminClient clientId=internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.
2022-06-22 13:53:48,856 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | command_response-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_239) [Producer clientId=command_response-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_239] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.
2022-06-22 13:53:48,857 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_238) [Producer clientId=event-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_238] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.
2022-06-22 13:53:48,858 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_238) [Producer clientId=event-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_238] Bootstrap broker hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless:9092 (id: -1 rack: null) disconnected
2022-06-22 13:53:48,860 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | command_response-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_239) [Producer clientId=command_response-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_239] Bootstrap broker hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless:9092 (id: -1 rack: null) disconnected
2022-06-22 13:53:48,864 WARN  [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-0) [Consumer clientId=notification-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_2, groupId=5e32eee9-d39e-440b-b438-16b303f00a06] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.
2022-06-22 13:53:48,865 WARN  [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-0) [Consumer clientId=notification-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_2, groupId=5e32eee9-d39e-440b-b438-16b303f00a06] Bootstrap broker hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless:9092 (id: -1 rack: null) disconnected
2022-06-22 13:53:48,874 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | telemetry-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_237) [Producer clientId=telemetry-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_237] Connection to node -1 (hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless/10.244.0.12:9092) could not be established. Broker may not be available.

...
...
2022-06-22 13:54:17,384 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-admin-client-thread | internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0) [AdminClient clientId=internal-cmd-admin-hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0] Error connecting to node hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless.hono-22ob8mixkg.svc.cluster.local:9092 (id: 0 rack: null): java.net.UnknownHostException: hono-22ob8mixkg-kafka-0.hono-22ob8mixkg-kafka-headless.hono-22ob8mixkg.svc.cluster.local
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:513)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:172)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:985)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1080)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1321)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-06-22 13:54:18,450 WARN  [org.ecl.hon.cli.kaf.con.HonoKafkaConsumer] (vert.x-eventloop-thread-0) timed out waiting for rebalance and update of subscribed topics
2022-06-22 13:54:18,736 DEBUG [org.ecl.hon.cli.com.kaf.KafkaBasedInternalCommandConsumer] (vert.x-eventloop-thread-1) created topic [hono.command_internal.hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0]
2022-06-22 13:54:18,739 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumer]
2022-06-22 13:54:18,749 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-1) successfully created client [type: io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl]
2022-06-22 13:54:18,781 DEBUG [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (vert.x-eventloop-thread-1) registered consumer (1 consumers total)
2022-06-22 13:54:18,957 DEBUG [org.ecl.hon.cli.kaf.con.HonoKafkaConsumer] (vert.x-kafka-consumer-thread-0) partitions assigned: [{hono.notification.registry-tenant=[0], hono.notification.registry-device=[0]}]
2022-06-22 13:54:19,483 DEBUG [org.ecl.hon.cli.kaf.con.HonoKafkaConsumer] (vert.x-kafka-consumer-thread-1) partitions assigned: [{hono.command_internal.hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0=[0]}]
2022-06-22 13:54:19,483 DEBUG [org.ecl.hon.cli.kaf.con.HonoKafkaConsumer] (vert.x-eventloop-thread-1) consumer started, subscribed to topics [hono.command_internal.hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0]
2022-06-22 13:54:26,789 INFO  [io.sma.health] (executor-thread-0) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Vert.x deployment","status":"UP","data":{"adapter verticle(s)":"successfully deployed","notification receiver verticle":"successfully deployed"}},{"name":"connection-to-Device Registration-24028f69-3c4e-464a-8703-468cf80e41db","status":"UP"},{"name":"connection-to-Command Router-32d842a3-8951-4d97-b2f6-323995774b76","status":"UP"},{"name":"command_response-kafka-producer-creation-4565be17-ad1f-4038-b19d-37fcd857c625","status":"UP"},{"name":"event-kafka-producer-creation-919d89e2-38df-4c30-8549-6e365e92fa35","status":"UP"},{"name":"telemetry-kafka-producer-creation-20ad084c-6d38-48a5-99db-47c625b8889d","status":"UP"},{"name":"notification-kafka-consumer-creation-08788853-61cd-4cfb-b41d-0b8d2ddcfa51","status":"DOWN"},{"name":"connection-to-Tenant-6e887ee2-1440-434c-90f4-909e39267fb7","status":"UP"},{"name":"internal-command-consumer[hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0]-readiness","status":"UP"},{"name":"connection-to-Credentials-b3a0ad2a-83ca-40a3-8bba-f62752a61e8b","status":"UP"}]}
2022-06-22 13:54:36,790 INFO  [io.sma.health] (executor-thread-0) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Vert.x deployment","status":"UP","data":{"adapter verticle(s)":"successfully deployed","notification receiver verticle":"successfully deployed"}},{"name":"connection-to-Device Registration-24028f69-3c4e-464a-8703-468cf80e41db","status":"UP"},{"name":"connection-to-Command Router-32d842a3-8951-4d97-b2f6-323995774b76","status":"UP"},{"name":"command_response-kafka-producer-creation-4565be17-ad1f-4038-b19d-37fcd857c625","status":"UP"},{"name":"event-kafka-producer-creation-919d89e2-38df-4c30-8549-6e365e92fa35","status":"UP"},{"name":"telemetry-kafka-producer-creation-20ad084c-6d38-48a5-99db-47c625b8889d","status":"UP"},{"name":"notification-kafka-consumer-creation-08788853-61cd-4cfb-b41d-0b8d2ddcfa51","status":"DOWN"},{"name":"connection-to-Tenant-6e887ee2-1440-434c-90f4-909e39267fb7","status":"UP"},{"name":"internal-command-consumer[hono-22ob8mixkg-adapter-mqtt-794f9576-vn669_1ecee34c81aa_0]-readiness","status":"UP"},{"name":"connection-to-Credentials-b3a0ad2a-83ca-40a3-8bba-f62752a61e8b","status":"UP"}]}
```

The log seems to suggest that the underlying KafkaClient is able to connect to the broker and the Hono component then creates the producers and consumers, but then the connection to the Kafka broker fails (because it gets restarted).
About 30s later, the broker is up again and some of the producers and consumers are successfully initialized. However, the consumer for the notifications topic runs into a timeout
```sh
2022-06-22 13:54:18,450 WARN  [org.ecl.hon.cli.kaf.con.HonoKafkaConsumer] (vert.x-eventloop-thread-0) timed out waiting for rebalance and update of subscribed topics
```
but never tries again to subscribe and for the rebalancing. As a consequence, the Hono component never reaches the ready state as can be seen from the failed readiness probe invocations.

This should not be a big issue in production environments, though, because there we usually find am already running multi-node Kafka broker being used. However, I wonder if we can simply remove the timer that we are running into and rely on the underlying Kafka client to successfully subscribe and assign the partitions once the broker is up and running again. At least the log seems to suggest that this what's actually happening ...

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #3312:
A restarting Kafka broker could have caused a timeout while waiting for the initial Kafka consumer rebalance in `subscribeAndWaitForRebalance()`, meaning that in this scenario the HonoKafkaConsumer couldn't get ready.

Also readiness-check log output in Kafka consumer classes gets improved here.

The changes are deliberately kept small here in order to reduce the potential impact when merging into 2.0.x.

I'm looking into doing some further improvements for 2.1.0, also in connection with #3349.

### CODE REVIEW

File: clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java [hunk 1]
```diff
@@ -530,7 +530,20 @@ public void registerLivenessChecks(final HealthCheckHandler livenessHandler) {
...
-                status -> status.tryComplete(new Status().setOk(lifecycleStatus.isStarted())));
+                status -> {
+                    if (lifecycleStatus.isStarted()) {
+                        status.tryComplete(Status.OK());
+                    } else {
+                        if (lifecycleStatus.isStarting()) {
+                            if (kafkaConsumer == null) {
+                                LOG.debug("readiness check failed, consumer not created yet");
+                            } else {
+                                LOG.debug("readiness check failed, consumer initialization not finished yet");
```
Comment (sophokles73) [inline clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java:541]: how about putting this info into the Status as well?

File: clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java [hunk 2]
```diff
@@ -855,24 +868,28 @@ private Future<Void> subscribeAndWaitForRebalance() {
...
+                            LOG.info("subscription topic doesn't exist as of now: {} [client-id: {}]", topic, getClientId());
                         }
                     }));
             kafkaConsumer.subscribe(topics, subscriptionUpdated);
         }
         // init kafkaConsumerWorker if needed; it has to be retrieved after the first "subscribe" invocation
         if (kafkaConsumerWorker == null) {
             kafkaConsumerWorker = getKafkaConsumerWorker(kafkaConsumer);
+        } else {
+            // not the first "subscribe" invocation;
```
Comment (sophokles73) [inline clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java:881]: when is this supposed to happen? I do not quite understand if this is a branch that we will regularly run into or if this would be the result of *mis-using* the API ...

Comment (calohmn) [reply clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java:881]: The `subscribeAndWaitForRebalance` method is invoked in two kinds of scenarios:
- once on initialization of the consumer; lifecycleStatus is `starting`,
- in the `ensureTopicIsAmongSubscribedTopicPatternTopics` method (invoked as part of the Command Router `register-cmd-consumer` handling); lifecycleStatus is `started` here.

Therefore, the `// not the first "subscribe" invocation;` branch above will only be called in case of the `ensureTopicIsAmongSubscribedTopicPatternTopics` invocation.

I'm currently working on a further refactoring, also making `ensureTopicIsAmongSubscribedTopicPatternTopics` simpler. This shall make the timer handling above unnecessary.

**Review by sophokles73 — APPROVED** [review]

**Comment by calohmn** [comment]
(further improved readiness check output)
