### PR TITLE
[#3014] Fix handling on cmd consumer re-joining consumer group

### LINKED ISSUE #3014: Prevent long command processing delays in protocol adapter if Kafka consumer partitions get reassigned
We have observed a case where there was a delay of several minutes in a protocol adapter handling (Kafka-based) command messages forwarded by the Command Router.

Protocol adapter logs showed that the Kafka command consumer client noticed an intermittent unavailability of the group coordinator node (due to Kafka node restart?) and a subsequent new partition assignment, resulting in an offset reset:
```
18:11:22.126 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Group coordinator kafka-host:9092 (id: 123 rack: null) is unavailable or invalid, will attempt rediscovery

18:11:22.282 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Discovered group coordinator kafka-host:9092 (id: 123 rack: null)

18:11:29.383 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Giving away all assigned partitions as lost since generation has been reset,indicating that consumer is no longer part of the group

18:11:29.383 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Lost previously assigned partitions hono.command_internal.hono-adapter-coap-vertx-v2-x-0


18:11:29.387 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] (Re-)joining group

18:11:29.398 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Adding newly assigned partitions: hono.command_internal.hono-adapter-coap-vertx-v2-x-0

18:11:29.401 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Found no committed offset for partition hono.command_internal.hono-adapter-coap-vertx-v2-x-0

18:11:29.435 [Consumer clientId=hono-coap-adapter-consumer-internal-cmd-624e926f-9f9c-4bfd-95c8-643356f922e9, groupId=hono-adapter-coap-vertx-v2-x] Resetting offset for partition hono.command_internal.hono-adapter-coap-vertx-v2-x-0 to offset 11087717.
```
Since the offset reset policy is set to EARLIEST and no offsets are committed, this means that the command consumer client re-read all of the command records stored in the adapter-instance specific topic - these were quite many.
No duplicate commands were sent to devices since there is a detection of command messages having been handled before (see #2480) but the problem is that going through all these records again caused the processing of newly received commands to get delayed.
It took several minutes to reduce the consumer lag down to zero and begin handling new commands again.

In general, we need to fix the `KafkaBasedInternalCommandConsumer` here to actually do offset commits, so that such Kafka node failures/restarts don't result in potentially lots of records being re-read.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #3014:
Enable offset auto-commit on internal command topic consumer so that offsets get properly reset after a partition re-assignment (e.g. due to Kafka node restart). Also fix the mechanism that skips already handled commands, preventing duplicate handling in case initial record handling found no command handler or got an error fetching tenant information.

### CODE REVIEW

File: clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java [hunk 1]
```diff
@@ -393,46 +392,47 @@ void handleCommandMessage(final KafkaConsumerRecord<String, Buffer> record) {
...
-                    commandContext.release(new NoConsumerException("no command handler found for command"));
-                }
-            });
+        // partition index and offset here are related to the *tenant-based* topic the command was originally received in
+        // therefore they are stored with the tenant as key
+        final Map<Integer, Long> lastHandledPartitionOffsets = lastHandledPartitionOffsetsPerTenant
+                .computeIfAbsent(command.getTenant(), k -> new HashMap<>());
+        final Long lastHandledOffset = lastHandledPartitionOffsets.get(commandPartition);
+        if (lastHandledOffset != null && commandOffset <= lastHandledOffset) {
+            LOG.debug("ignoring command - record partition offset {} <= last handled offset {} [{}]", commandOffset,
```
Comment (sophokles73) [inline clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java:405]: this should be guarded by a check if debug level is enabled on the logger to prevent the command object's toString() method to be invoked unnecessarily

File: clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java [hunk 2]
```diff
@@ -393,46 +392,47 @@ void handleCommandMessage(final KafkaConsumerRecord<String, Buffer> record) {
...
+                    lastHandledOffset, command);
+            TracingHelper.logError(currentSpan, "command record already handled before");
```
Comment (sophokles73) [inline clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java:407]: is this an error? I would assume we can simply silently ignore the duplicate or can't we?

File: clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java [hunk 3]
```diff
@@ -393,46 +392,47 @@ void handleCommandMessage(final KafkaConsumerRecord<String, Buffer> record) {
...
+            commandContext.release(new CommandAlreadyProcessedException());
+        } else {
+            lastHandledPartitionOffsets.put(commandPartition, commandOffset);
```
Comment (sophokles73) [inline clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java:410]: do we really want to mark it as processed here already? what if the tenant config cannot be retrieved right now but could be retrieved on the next attempt?

File: clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java (hunk 2 above)
Comment (calohmn) [reply clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java]: I've removed this line and the following here, also not creating a span for this case.

File: clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java (hunk 1 above)
Comment (calohmn) [reply clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java]: I've added that.

**Review by sophokles73 — APPROVED** [review]
LGTM
