### PR TITLE
[#1718] Add exception handling; improve link creation logic

### LINKED ISSUE #1718: Rare sender/receiver creation error
We have seen the following error in a protocol adapter log while the AMQP messaging network component got restarted:
````
15:26:17.575 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - link establishment [peer: xx] timed out after 1000ms
15:26:17.576 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonReceiverImpl.free(ProtonReceiverImpl.java:41)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````
This caused the receiver creation future to not get finished.

<details>
<summary>Here is another variant of this stacktrace.</summary>

~~~
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.SessionImpl.postFinal(SessionImpl.java:138)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonReceiverImpl.free(ProtonReceiverImpl.java:41)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

</details>

<details>
<summary>And here another during *sender* creation.</summary>

~~~
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonSenderImpl.free(ProtonSenderImpl.java:33)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createSender$12(HonoConnectionImpl.java:698)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

~~~

</details>

The errors above lead to the assumption that somehow one of the Proton Link/Session/Connection/Transport objects got corrupted.
An explanation could be that there was an exception in one of the handlers associated with these objects (e.g. closeHandler, detachHandler, etc.).
Such exceptions don't get logged and cause a corrupted state of the Proton object (see https://github.com/vert-x3/vertx-proton/issues/94).
Therefore a solution could be to add exception handling for these handlers.

Another issue is that the `link establishment timed out` log message is misleading - the failure to establish the link is caused by the closed connection, not by the "attach" frame not getting received on an intact connection.

EDIT: the origin actually wasn't an unhandled exception thrown in one of the handlers - see [comment below](https://github.com/eclipse/hono/issues/1718#issuecomment-580672008).

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #1718.

Fix onLinkEstablishmentTimeout(), not calling link.free()
there anymore (has caused session to get into invalid state).
Exceptions now get caught in disconnect/detach/close handlers
used in HonoConnectionImpl. A disconnect during link creation
now causes the creation attempt to be failed directly,
without waiting for the link establishment timeout.

### CODE REVIEW

File: client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java [hunk 1]
```diff
@@ -648,6 +648,47 @@ public void testCreateReceiverFailsOnTimeout(final TestContext ctx) {
...
+        when(receiver.isOpen()).thenReturn(Boolean.TRUE);
+        when(receiver.getSource()).thenReturn(source);
+        when(receiver.getRemoteSource()).thenReturn(source);
+        when(con.createReceiver(anyString())).thenReturn(receiver);
+
+        // WHEN creating a receiver link with a close hook
+        final Handler<String> remoteCloseHook = mock(Handler.class);
+
+        final Future<ProtonReceiver> result = honoConnection.createReceiver("source", ProtonQoS.AT_LEAST_ONCE,
+                mock(ProtonMessageHandler.class), remoteCloseHook);
```
Comment (sophokles73) [inline client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java]: IMHO you also nee to verify that at this point the result is not completed/failed yet ...

File: client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java [hunk 2]
```diff
@@ -905,4 +946,44 @@ public void testCreateSenderThatGetsDelayedCredits(final TestContext ctx) {
...
+        // mock handlers
+        final Handler<String> remoteCloseHook = mock(Handler.class);
+
+        // GIVEN an established connection
+        final Async connectAttempt = ctx.async();
+        honoConnection.connect().setHandler(ctx.asyncAssertSuccess(ok -> connectAttempt.complete()));
+        connectAttempt.await();
+
+        final Future<ProtonSender> result = honoConnection.createSender(
+                "target", ProtonQoS.AT_LEAST_ONCE, remoteCloseHook);
```
Comment (sophokles73) [inline client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java]: same here

File: core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java [hunk 3]
```diff
@@ -60,7 +65,11 @@ private HonoProtonHelper() {
         Objects.requireNonNull(handler);
 
         final Handler<AsyncResult<T>> wrappedHandler = remoteDetach -> {
-            handler.handle(remoteDetach);
+            try {
+                handler.handle(remoteDetach);
+            } catch (final Exception ex) {
+                LOG.warn("error running detachHandler", ex);
+            }
             link.free();
```
Comment (sophokles73) [inline core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java]: didn't one of the stack traces you showed me that a runtime exception had been thrown while executing the *free()* method?

**Comment by sophokles73** [comment]
@calohmn any update here?

**Comment by calohmn** [comment]
@sophokles73 I'm now able to reproduce the exception from #1718 in a long-running test. However, the actual cause of the exception (and a way to reproduce it in a simpler setup or unit test) is not yet clear to me. I'm currently doing more tests and then see how to adapt this PR accordingly.

**Comment by sophokles73** [comment]
@calohmn can you rebase?

File: core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java (hunk 3 above)
Comment (calohmn) [reply core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java]: yes, but now these exceptions in *free()* shouldn't happen anymore.

**Comment by calohmn** [comment]
@sophokles73 Done. PR now contains the changes concerning the latest comment in the issue.
