### PR TITLE
Return proper error detail in credentials resource responses

### LINKED ISSUE #2471: Device Registry: Error responses do not comply with the specification
The current device registry implementations _(File, JDBC and MongoDB)_  return error responses that do not comply with the below _schema_ as defined by the [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/).

```
      Error:
         type: object
         additionalProperties: true
         required:
            - error
         properties:
            "error":
               type: string
               description: A human readable error message of what went wrong.
```

Currently I see two patterns, in case of error responses being returned by the device registries.

1. The first pattern is an error response of type `String`. 
     Example: While trying to register a tenant with invalid payload json, then the response status code is `400 Bad Request`  
     with an error response as `request does not contain a valid Tenant object`

2. The second pattern is that the error response is simply _null_. 
     Example: Try to update an existing information with an invalid resource version. Then the returned response status code is  `412 Precondition Failed` with _null_ as the error response.

### PR DESCRIPTION
**Pull request by sophokles73**
The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"credentials" resources.

Fixes #2471

### CODE REVIEW

File: services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java [hunk 1]
```diff
@@ -167,7 +170,7 @@ public void setTenantInformationService(final TenantInformationService tenantInf
                                     resourceVersion,
                                     span));
                 })
-                .otherwise(t -> DeviceRegistryUtils.mapErrorToResult(t, span));
```
Comment (calohmn) [inline services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java:170]: `DeviceRegistryUtils.mapErrorToResult` can now be removed.

Comment (sophokles73) [reply services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java:170]: I have pushed corresponding changes

**Review by calohmn — APPROVED** [review]
LGTM
