### PR TITLE
[#3297] Set fixed span name for invalid HTTP requests

### LINKED ISSUE #3297: HTTP request tracing: Trace names with high cardinality created for invalid requests
HTTP requests received by the Hono HTTP protocol adapter or device registry should appear in the tracing UI either with the name of the specific, matched route (e.g. `/telemetry`) or with a catch-all name (`/* (default route)`). Notably, trace names should not be adopted from the HTTP request path as is, otherwise the span selection combobox in the tracing UI will be cluttered with unwanted entries.

However, with the current tracing implementation, there are cases where the span name indeed gets wrongly set to the HTTP request path. This seems to occur for invalid HTTP requests, where the path does not begin with a slash.

Example:
WrongSpanName

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #3297.

### CODE REVIEW

File: adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java [hunk 1]
```diff
@@ -253,42 +256,48 @@ protected void onStartupSuccess() {
...
+
         final Router router = Router.router(vertx);
+        final DefaultFailureHandler defaultFailureHandler = new DefaultFailureHandler();
         final Route matchAllFailuresRoute = router.route();
-        // failure handler is added on a separate route for which no name is set, otherwise all tracing spans
-        // of failed HTTP requests would get that route name as span name
-        matchAllFailuresRoute.failureHandler(new DefaultFailureHandler());
+        // failure handler is added on a separate route with no name (the HTTP request root span name is taken from
+        // the last-applied named route, we don't want to overwrite the name of a specific route here)
+        matchAllFailuresRoute.failureHandler(ctx -> {
```
Comment (sophokles73) [inline adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java:280]: is it by intention that we are creating two Route instances that match any URI, i.e. matchAllFailuresRoute and matchAllRoute? Or would it be sufficient to just create *matchAllRoute* and set this failure handler on it?

**Comment by calohmn** [comment]
What is still a bit inconsistent is that 404 requests don't get marked with an error tag in the tracing span. I've created #3299 to address that.
