### PR TITLE
Return proper error detail in devices resource responses

### LINKED ISSUE #2471: Device Registry: Error responses do not comply with the specification
The current device registry implementations _(File, JDBC and MongoDB)_  return error responses that do not comply with the below _schema_ as defined by the [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/).

```
      Error:
         type: object
         additionalProperties: true
         required:
            - error
         properties:
            "error":
               type: string
               description: A human readable error message of what went wrong.
```

Currently I see two patterns, in case of error responses being returned by the device registries.

1. The first pattern is an error response of type `String`. 
     Example: While trying to register a tenant with invalid payload json, then the response status code is `400 Bad Request`  
     with an error response as `request does not contain a valid Tenant object`

2. The second pattern is that the error response is simply _null_. 
     Example: Try to update an existing information with an invalid resource version. Then the returned response status code is  `412 Precondition Failed` with _null_ as the error response.

### PR DESCRIPTION
**Pull request by sophokles73**
This is step 2 in a series of PR to fix #2471 

The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"devices" resources.

### CODE REVIEW

**Comment by sophokles73** [comment]
@calohmn would you mind taking a look? @kaniyan will probably not find the time ...

File: services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java [hunk 1]
```diff
@@ -340,26 +343,23 @@ default void testCreateDeviceFailsForExistingDeviceId(final VertxTestContext ctx
         final String deviceId = randomDeviceId();
 
         createDevice(deviceId, new Device())
-            .onComplete(ctx.succeeding(ok -> {}))
```
Comment (calohmn) [inline services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java:343]: It would be in line with the other tests to keep this here, making sure the first device creation succeeded.

File: services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java [hunk 2]
```diff
@@ -424,69 +421,98 @@ public void testDoStartIgnoreIdentitiesIfStartEmptyIsSet(final VertxTestContext
...
+                    Optional.of("newDevice"),
+                    new Device(),
+                    NoopSpan.INSTANCE))
+            .onComplete(ctx.failing(t -> {
+                // THEN the result contains a FORBIDDEN status code
+                ctx.verify(() -> Assertions.assertServiceInvocationException(t, HttpURLConnection.HTTP_FORBIDDEN));
+                registrationService.readDevice(TENANT, "newDevice", NoopSpan.INSTANCE)
+                    .onComplete(ctx.failing(error -> {
+                        // and the device has not been added to the registry
+                        ctx.verify(() -> org.eclipse.hono.deviceregistry.util.Assertions.assertServiceInvocationException(
```
Comment (calohmn) [inline services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java:446]: `org.eclipse.hono.deviceregistry.util.` superfluous here.

**Comment by sophokles73** [comment]
@calohmn I have pushed corresponding changes ...

**Review by calohmn — APPROVED** [review]
LGTM
