### PR TITLE
[#2180] Fix NPE if ResourceIdentifier string is empty

### LINKED ISSUE #2180: MQTT adapter: NPE when using empty publish topic
We have observed the following exception in the MQTT adapter:
````
ERROR io.vertx.core.impl.ContextImpl Unhandled exception
java.lang.NullPointerException: null
	at java.base/java.lang.StringBuilder.<init>(Unknown Source)
	at org.eclipse.hono.util.ResourceIdentifier.createStringRepresentation(ResourceIdentifier.java:153)
	at org.eclipse.hono.util.ResourceIdentifier.setResourcePath(ResourceIdentifier.java:104)
	at org.eclipse.hono.util.ResourceIdentifier.<init>(ResourceIdentifier.java:63)
	at org.eclipse.hono.util.ResourceIdentifier.fromString(ResourceIdentifier.java:175)
	at org.eclipse.hono.adapter.mqtt.MqttContext.lambda$fromPublishPacket$1(MqttContext.java:106)
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
	at org.eclipse.hono.adapter.mqtt.MqttContext.fromPublishPacket(MqttContext.java:103)
	at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.lambda$registerHandlers$64(AbstractVertxBasedMqttProtocolAdapter.java:1561)
	at io.vertx.mqtt.impl.MqttEndpointImpl.handlePublish(MqttEndpointImpl.java:528)
	at io.vertx.mqtt.impl.MqttServerConnection.handlePublish(MqttServerConnection.java:330)
	at io.vertx.mqtt.impl.MqttServerConnection.handleMessage(MqttServerConnection.java:143)
	at io.vertx.mqtt.impl.MqttServerImpl.lambda$null$3(MqttServerImpl.java:94)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
````
This must have occurred when the client has published a message with an empty topic.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #2180.
Improve error handling by explicitly checking for an empty string when creating a `ResourceIdentifier`.
Fix exception handling and javadoc comments concerning resource addresses.

### CODE REVIEW

File: core/src/main/java/org/eclipse/hono/util/MessageHelper.java [hunk 1]
```diff
@@ -1018,6 +1013,7 @@ public static Message newMessage(
             final boolean addDefaults,
             final boolean addJmsVendorProps) {
 
+        Objects.requireNonNull(target);
```
Comment (calohmn) [inline core/src/main/java/org/eclipse/hono/util/MessageHelper.java:1016]: Added `null` check:
If `target` were `null`, there would be an `IllegalArgumentException` thrown by the `addProperties` method here (already in the code before this PR).

**Review by sophokles73 — APPROVED** [review]
LGTM
