### PR TITLE
[#895] Don't create error span if no client certs were given

### LINKED ISSUE #895: HTTP-Adapter: misleading error trace if client certificate check failed (but basic auth succeeded)
Using the Hono HTTP adapter with Jaeger tracing enabled, we see traces like this:
http-adapter-trace

We use the device authentication via Basic Auth (which succeeded here) - the error above is about the failed attempt to verify the device using a client certificate (done before the basic auth check).

Having this marked as an error in the trace is somewhat misleading and makes it harder to filter the traces list for actual errors.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #895.

### CODE REVIEW

**Comment by calohmn** [comment]
I've amended the commit to minimize the changes.

With my first commit I wanted to make it clearer, where the `SSLPeerUnverifiedException` may actually get thrown (that is only in the line with the `getPeerCertificates()` invocation) by reducing the try-catch scope accordingly. This lead to introducing early exits for the common cases "no ssl used" and "no certs given".

Omitting the early exits but keeping the minimized try-catch block, I would suggest this further change:
```
            Certificate[] peerCerts = null;
            try {
                peerCerts = context.request().sslSession().getPeerCertificates();
            } catch (SSLPeerUnverifiedException e) {
                LOG.debug("could not get client certificates: " + e.getMessage());
            }
            if (peerCerts != null) {
                 //..
            } else {
                handler.handle(Future.failedFuture(UNAUTHORIZED));
            }
```

File: adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java [hunk 1]
```diff
@@ -190,8 +190,7 @@ public final void parseCredentials(final RoutingContext context, final Handler<A
                 });
             } catch (SSLPeerUnverifiedException e) {
                 // client certificate has not been validated
-                TracingHelper.logError(span, e);
-                span.finish();
+                LOG.debug("could not get client certificates: " + e.getMessage());
```
Comment (sophokles73) [inline adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java]: can you use the usual placeholder syntax for log statements, i.e.
`LOG.debug("could not get client certificates: {}", e.getMessage())`

Comment (calohmn) [reply adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java]: yes, I've changed that.
