### PR TITLE
Return proper error detail in tenants resource responses

### LINKED ISSUE #2471: Device Registry: Error responses do not comply with the specification
The current device registry implementations _(File, JDBC and MongoDB)_  return error responses that do not comply with the below _schema_ as defined by the [Device Registry Management API](https://www.eclipse.org/hono/docs/api/management/).

```
      Error:
         type: object
         additionalProperties: true
         required:
            - error
         properties:
            "error":
               type: string
               description: A human readable error message of what went wrong.
```

Currently I see two patterns, in case of error responses being returned by the device registries.

1. The first pattern is an error response of type `String`. 
     Example: While trying to register a tenant with invalid payload json, then the response status code is `400 Bad Request`  
     with an error response as `request does not contain a valid Tenant object`

2. The second pattern is that the error response is simply _null_. 
     Example: Try to update an existing information with an invalid resource version. Then the returned response status code is  `412 Precondition Failed` with _null_ as the error response.

### PR DESCRIPTION
**Pull request by sophokles73**
This is the first PR in a series to fix #2471

The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"tenants" resources.

### CODE REVIEW

File: services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java [hunk 1]
```diff
@@ -360,64 +357,56 @@ private void addTenant(final JsonObject tenantToAdd) {
...
+                            tenantId,
+                            HttpURLConnection.HTTP_PRECON_FAILED,
+                            "resource Version mismatch"));
                 }
             } else {
                 TracingHelper.logError(span, "Tenant not found.");
-                return Result.from(HttpURLConnection.HTTP_NOT_FOUND);
+                return Future.failedFuture(new ClientErrorException(
+                        tenantId,
+                        HttpURLConnection.HTTP_NOT_FOUND));
```
Comment (kaniyan) [inline services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java:378]: How about also adding a corresponding error message in case of _HTTP_NOT_FOUND_ ? So that the error json has some meaningful message instead of `N/A`.

**Review by kaniyan — CHANGES_REQUESTED** [review]

File: services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java (hunk 1 above)
Comment (sophokles73) [reply services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java]: I have pushed corresponding changes

**Review by kaniyan — APPROVED** [review]
LGTM
