### PR TITLE
Pick up Kafka client ID prefix configuration property

### LINKED ISSUE #2960: Quarkus images with Kafka: hono.kafka.defaultClientIdPrefix does not map to any root
When starting current master Quarkus images with Kafka, using the IoT Packages Helm chart, there is this exception
```
Nov 18, 2021 2:33:11 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.smallrye.config.ConfigValidationException: Configuration validation failed:
	hono.kafka.defaultClientIdPrefix does not map to any root
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:855)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:403)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1293)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:326)
```

### PR DESCRIPTION
**Pull request by sophokles73**
The Quarkus based components did not support the "defaultClientIdPrefix"
configuration property of the Kafka client.

Fixes #2960

### CODE REVIEW

**Comment by sophokles73** [comment]
@calohmn would you mind taking a  look?

File: adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java [hunk 1]
```diff
@@ -222,15 +222,23 @@ void setConnectionEventProducerConfig(final ConnectionEventProducerOptions optio
...
+        final Optional<String> clientIdPrefix = Optional.ofNullable(
+                options.defaultClientIdPrefix().orElse(getComponentName()));
+
         this.kafkaProducerConfig = new MessagingKafkaProducerConfigProperties();
+        clientIdPrefix.ifPresent(this.kafkaProducerConfig::setDefaultClientIdPrefix);
         this.kafkaProducerConfig.setCommonClientConfig(options.commonClientConfig());
         this.kafkaProducerConfig.setProducerConfig(options.producerConfig());
 
         this.kafkaConsumerConfig = new MessagingKafkaConsumerConfigProperties();
+        this.kafkaConsumerConfig.setDefaultClientIdPrefix(options.defaultClientIdPrefix().orElse(getComponentName()));
```
Comment (calohmn) [inline adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java:235]: This line looks superfluous.

File: site/documentation/content/admin-guide/hono-kafka-client-configuration.md [hunk 2]
```diff
@@ -3,20 +3,24 @@ title = "Hono Kafka Client Configuration"
...
-## Configure for Kafka based Messaging
+## Configuring Tenants to use Kafka based Messaging
+
+Hono's components by default support using AQMP 1.0 based messaging infrastructure to transmit messages hence and forth
+between devices and applications. Hono also supports using Kafka as the messaging infrastructure either as a replacement
+for or as an alternative in addition to the AMQP 1.0 based infrastructure.
+
+All tenants configured in Hono use the AMQP 1.0 based infrastructure by default. A tenant can also be configured
+to use Kafka instead of AMQP 1.0 by means of adding the property `ext/messaging-type` with value `kafka` to the
+[tenant's configuration]({{< relref "/api/tenant#tenant-information-format" >}}) in the registry.
```
Comment (calohmn) [inline site/documentation/content/admin-guide/hono-kafka-client-configuration.md:22]: (Typo: AQMP)

I think it would be good to point out at the beginning here already (instead of in the info box below), that this is only relevant if *both* messaging systems have been configured. 
In the usual case that only one messaging system is used, the reader can skip this section then.

**Review by calohmn — APPROVED** [review]
LGTM
