### PR TITLE
Adapt connection limit strategy to VM being used

### LINKED ISSUE #2675: Quarkus native image based adapters compute wrong max number of connections
The `MemoryBasedConnectionLimitStrategy` that is used by the protocol adapters determines the recommended maximum number of connections per adapter instance based on the amount of memory that the adapter needs to run and the memory required for each connection.
The memory to run the adapter depends on whether the adapter runs on a standard JVM or on the Substrate VM. The native images run on the Substrate VM and require a lot less memory to run than the JVM variant.
When configuring a native image based adapter container with less memory than the minimum amount of memory required to run the adapter (which is hard coded into the adapter), then startup of the container fails because the maximum number of connections is determined to be 0.

### PR DESCRIPTION
**Pull request by sophokles73**
The protocol adapters use the MemoryBasedConnectionLimitStrategy to
determine the number of connections that can be established with devices
based on the memory available to the adapter process.

The adapters currently assume to be running on a standard Java VM and
therefore assess the minimum amount of memory required for running to be
100MB (excluding memory allocated for device connections).

When using the Quarkus based native images, the memory footprint of the
adapters is significantly lower. This is now reflected in the MQTT and
AMQP adapters which first check the type of VM they are running on and
then adapt the minimum required memory accordingly.

Fixes #2675

### CODE REVIEW

**Comment by kaniyan** [comment]
I see that the connection limit strategy is also being used to set the maximum DTLS connections accepted by COAP adapter. Anyway the stale connections are evicted first if max limit is reached. COAP adapter test config still contain `maxConnections` configured and may be that can be removed too to make use of the memory strategy.


Quarkus native images are also used in Sandbox deployment and may be `maxConnections` to be removed from the AMQP, MQTT and COAP adpaters config there as well so that the memory strategy get employed.

**Comment by sophokles73** [comment]
> Quarkus native images are also used in Sandbox deployment and may be maxConnections to be removed from the AMQP, MQTT and COAP adpaters config there as well so that the memory strategy get employed.

We can do that once we have release 1.9.0 and these changes are in effect.

File: adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java [hunk 1]
```diff
@@ -105,14 +105,19 @@
 
     // These values should be made configurable.
     /**
-     * The minimum amount of memory that the adapter requires to run.
+     * The minimum amount of memory (bytes) that the adapter requires to run on a standard Java VM.
      */
-    private static final int MINIMAL_MEMORY = 100_000_000; // 100MB: minimal memory necessary for startup
+    private static final int MINIMAL_MEMORY_JVM = 100_000_000;
```
Comment (dejanb) [inline adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java:110]: Should we move these to the abstract adapter or even limit strategy class, so we don't have to repeat it for every adapter?

Comment (sophokles73) [reply adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java:110]: That would, of course, make sense if the values would be the same for all adapters by definition. However, in general, I guess these are adapter (type) specific, aren't they?

Comment (dejanb) [reply adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java:110]: I supposed these were reasonable defaults for most of the adapters, that could be overridden if needed. Anyhow, the PR looks good to me.

**Review by kaniyan — APPROVED** [review]
LGTM
