### PR TITLE
Consider SSLException terminal for connection attempt.

### LINKED ISSUE #1424: HonoClient endlessly retries to establish connection that fails due to SSL exception
When the client tries to open a connection to a service and the TLS handshake fails, the client re-tries forever to establish the connection.
However, the handshake failure will most likely not go away without reconfiguring the client and/or server. Thus, the SSLException should be considered a *terminal error* that stops the client from re-trying.

### PR DESCRIPTION
**Pull request by sophokles73**
The HonoClient now stops a connection attempt if it runs into an
SSLException which indicates a permanent problem with the TLS handshake.

Fixes #1424

### CODE REVIEW

File: client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java [hunk 1]
```diff
@@ -541,6 +543,10 @@ private void failConnectionAttempt(final Throwable connectionFailureCause, final
         } else if (connectionFailureCause instanceof MechanismMismatchException) {
             connectionHandler.handle(Future.failedFuture(
                     new ClientErrorException(HttpURLConnection.HTTP_UNAUTHORIZED, "no suitable SASL mechanism found for authentication with server")));
+        } else if (connectionFailureCause instanceof SSLException) {
+            connectionHandler.handle(Future.failedFuture(
+                    new ClientErrorException(HttpURLConnection.HTTP_UNAUTHORIZED,
+                            "TLS handshake with server failed: " + connectionFailureCause.getMessage())));
```
Comment (ctron) [inline client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: I think it is helpful to have the root cause as well, instead of only having the top message.

Comment (sophokles73) [reply client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: I have pushed a corresponding change ...

File: client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java [hunk 2]
```diff
@@ -541,6 +543,10 @@ private void failConnectionAttempt(final Throwable connectionFailureCause, final
         } else if (connectionFailureCause instanceof MechanismMismatchException) {
             connectionHandler.handle(Future.failedFuture(
                     new ClientErrorException(HttpURLConnection.HTTP_UNAUTHORIZED, "no suitable SASL mechanism found for authentication with server")));
+        } else if (connectionFailureCause instanceof SSLException) {
+            connectionHandler.handle(Future.failedFuture(
+                    new ClientErrorException(HttpURLConnection.HTTP_UNAUTHORIZED,
```
Comment (calohmn) [inline client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: Wouldn't a `400 Bad Request` be more appropriate here?
(Possibly `401 Unauthorized` could be tied to the `SSLPeerUnverifiedException` subclass of `SSLException`, although I wonder if that can occur here.)

File: tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java [hunk 3]
```diff
@@ -53,27 +56,51 @@ public static void init() {
...
+        downstreamProps.setReconnectAttempts(-1);
+
+        clientFactory = IntegrationTestApplicationClientFactory.create(HonoConnection.newConnection(vertx, downstreamProps));
+        // WHEN the client tries to connect
+        clientFactory.connect().setHandler(ctx.failing(t -> {
+            // THEN the connection attempt fails due to lack of authorization
+            ctx.verify(() -> {
+                assertThat(ServiceInvocationException.extractStatusCode(t)).isEqualTo(HttpURLConnection.HTTP_UNAUTHORIZED);
+            });
+        ctx.completeNow();
```
Comment (calohmn) [inline tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java]: indentation

File: client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java (hunk 2 above)
Comment (sophokles73) [reply client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: I gave that a lot of thought as well :-) You could also try to use a more specific exception for `SSLKeyException`. However, since it is used to report problems with both the client as well as the server cert, you don't exactly know if it should be a `ClientErrorException` or a `ServerErrorException`.
I had also thought about just using a 400 code but again, the problem may also lie on the server side, so it is hard to do the exact right thing here.
I am fine with using the 400 code but I think we should stick with a single exception (and code) that we use for all TLS related problems for simplicity. In the end, we are also including the root cause which might be used to better understand the underlying problem. In any case, the SSLException should be considered a terminal condition ...

**Comment by sophokles73** [comment]
@ctron @calohmn anything else we need to change?

File: client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java (hunk 2 above)
Comment (calohmn) [reply client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: Ok, I would opt for using `400 Bad Request` as the single exception then.
Otherwise an "unauthorized" exception could be confusing in the case that there is an issue with incompatible cipher suites for example.

Comment (sophokles73) [reply client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java]: done

**Comment by sophokles73** [comment]
@calohmn can you take another look?
