### PR TITLE
[#2660] Prevent "already creating client for key" errors

### LINKED ISSUE #2660: Investigate "already creating client for key" when registering command consumer
There have been some integration test failures with an `error registering consumer with the command router service` failure.
The cause here was a `already creating client for key` error when trying to create the AMQP sender link between the AMQP protocol adapter and the Command Router component.

````
2021-05-14T16:56:28.8645075Z 16:56:28.859 [main] INFO  o.e.h.t.amqp.CommandAndControlAmqpIT - running testSendCommandFailsForCommandRejectedByDevice(AmqpCommandEndpointConfiguration, VertxTestContext) [3]; parameters: subscribe as: GATEWAY_FOR_SINGLE_DEVICE, southbound endpoint: command, northbound endpoint: command
[...]
2021-05-14T16:56:29.0529884Z 16:56:29.052 [vert.x-eventloop-thread-0] INFO  o.e.h.t.amqp.CommandAndControlAmqpIT - AMQPS connection to adapter [localhost:49175] established

2021-05-14T16:56:29.1265809Z AMQP2021-05-14 16:56:29,122 INFO  [org.ecl.hon.ada.cli.com.CommandRouterCommandConsumerFactory] (vert.x-eventloop-thread-0) error registering consumer with the command router service [tenant: 67b741f0-9795-4490-9380-f8d7cb95717f, device: 9e9c2880-d89b-4c22-bfbb-6dd35ecbcb43]: org.eclipse.hono.client.ServerErrorException: already creating client for key
2021-05-14T16:56:29.1270949Z AMQP	at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:215)
2021-05-14T16:56:29.1275020Z AMQP	at org.eclipse.hono.client.impl.CachingClientFactory.lambda$getOrCreateClient$3(CachingClientFactory.java:211)
2021-05-14T16:56:29.1278666Z AMQP	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:942)
[...]
2021-05-14T16:56:29.1567089Z AMQP	at java.base/java.lang.Thread.run(Unknown Source)
2021-05-14T16:56:29.1567701Z AMQP
2021-05-14T16:56:29.1569387Z 16:56:29.145 [vert.x-eventloop-thread-0] WARN  i.v.proton.impl.ProtonSessionImpl - Receiver closed with error
2021-05-14T16:56:29.1571888Z io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:precondition-failed, description='Temporarily unavailable', info=null}
````
Debug log output would have been
````
already trying to create a client for [{}] (max retries reached)
````
(number of retries is 3 with 20ms delay in between)

It should be investigated in how far such error situations can be prevented.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #2660:
Concurrent `CachingClientFactory.getOrCreateClient()` invocations are now completed along with the initial creation request.

### CODE REVIEW

**Comment by sophokles73** [comment]
I guess by *concurrent* you mean something like this:

1. component A invokes *CachingClientFactory.getOrCreate("the-key", ..., resultHandlerA)*
1. component B invokes *CachingClientFactory.getOrCreate("the-key", ..., resultHandlerB)*
1. resultHandlerA is called back with result

and now we want resultHandlerB to be invoked with the same result without invoking the supplier multiple times, right?

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java [hunk 1]
```diff
@@ -146,74 +173,139 @@ public void getOrCreateClient(
...
+                creationLocks.remove(key);
+                creationRequests.remove(connectionFailureHandler);
+                log.error("exception creating new client for [{}]", key, ex);
+                activeClients.remove(key);
+                final ServerErrorException exception = new ServerErrorException(HttpURLConnection.HTTP_INTERNAL_ERROR,
+                        String.format("exception creating new client for [%s]: %s", key, ex.getMessage()));
+                result.handle(Future.failedFuture(exception));
+                failWaitingCreationRequests(key, exception);
+            }
+            if (clientInstanceSupplierFuture != null) {
```
Comment (sophokles73) [inline clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:224]: if we explicitly check for the supplier to actually return a Future, then I guess we should also explicitly handle the case when it doesn't, shouldn't we?

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java [hunk 2]
```diff
@@ -63,9 +59,23 @@
...
     /**
-     * The locks for guarding the creation of new instances.
+     * The locks for guarding the creation of new instances. Map key is the client cache key.
      */
     private final Map<String, Boolean> creationLocks = new HashMap<>();
+    /**
+     * List of request data for client creation requests that are put on hold because
+     * a concurrent request is still not completed.
+     */
+    private final List<CreationRequestData> waitingCreationRequests = new LinkedList<>();
```
Comment (sophokles73) [inline clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:69]: wouldn't access to the requests be more efficient if we used a Map<String, Deque<CreationRequestData>> instead? We then wouldn't need to iterate over all elements every time a request for a particular key fails/succeeds, would we?

**Comment by calohmn** [comment]
> I guess by _concurrent_ you mean something like this:
> 
>     1. component A invokes _CachingClientFactory.getOrCreate("the-key", ..., resultHandlerA)_
> 
>     2. component B invokes _CachingClientFactory.getOrCreate("the-key", ..., resultHandlerB)_
> 
>     3. resultHandlerA is called back with result
> 
> 
> and now we want resultHandlerB to be invoked with the same result without invoking the supplier multiple times, right?

Yes. With the changes in this PR, resultHandlerB will also be invoked sooner (it isn't associated with a `setTimer` invocation any more) and the "already creating client for key" error, which is not revealing what the actual problem is (maybe multiple timeouts establishing the connection), is not being thrown any more.
And the implementation in this PR makes sure that the result handler invocation is done in the same order that the `getOrCreate` invocation was done - with regard to requests using the same key. The previous implementation could have ultimately led to older telemetry/event messages getting forwarded after newer ones, I guess.

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java [hunk 3]
```diff
@@ -38,17 +38,19 @@
...
+     * Each request is represented by the handler to be invoked to complete the request.
      */
     protected final List<Handler<Void>> creationRequests = new ArrayList<>();
 
     /**
-     * Clears all state.
+     * Clears all state. Meant to be invoked when the service connection was lost.
      * <p>
-     * All pending creation requests are failed.
+     * All pending creation requests are failed (see {@link #createConnectionLostException()}).
```
[the remark this answers is not in the document]
Comment (calohmn) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java]: I've refactored this method, making it clearer how pending requests are handled.

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java [hunk 4]
```diff
@@ -89,4 +92,13 @@ public final void createClient(
                 result.handle(attempt);
             });
     }
+
+    /**
+     * Creates the exception to be used for client creation failures due to a lost connection.
+     *
```
[the remark this answers is not in the document]
Comment (calohmn) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java]: I've removed this method now.

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java [hunk 5]
```diff
@@ -78,6 +88,22 @@ public CachingClientFactory(final Vertx vertx, final Predicate<T> livenessCheck)
         this.livenessCheck = Objects.requireNonNull(livenessCheck);
     }
 
+    /**
+     * Sets the number of client creation requests to complete in a row, when a creation request has
+     * succeeded and corresponding concurrently started creation requests are to be completed.
```
[the remark this answers is not in the document]
Comment (calohmn) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:95]: When the original request fails, all waiting requests with the same key are failed directly, without `vertx.runOnContext` and `waitingCreationRequestsCompletionBatchSize` being used (see `failWaitingCreationRequests`). Therefore `setWaitingCreationRequestsCompletionBatchSize` only applies to *succeeded* requests.

FMPOV it's better to use a fail-fast strategy here, not adding any delays by using `vertx.runOnContext`. The "failed" state is only a temporary one, a subsequent request a few milliseconds later could succeed.

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java (hunk 1 above)
Comment (calohmn) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:221]: I've added a `null` check for the returned Future now.

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java (hunk 2 above)
Comment (calohmn) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:71]: I've deliberately chosen a data structure to keep the request order across requests with different keys.

As an example, let's say there are client creation requests for `keyA`, 2 times `keyB`, and then 100 times `keyA`.
When creation for `keyA` succeeds, the first 10 ( `WAITING_CREATION_REQUESTS_COMPLETION_BATCH_SIZE_DEFAULT`) of the 100 waiting `keyA` requests will get handled.
When in the mean time creation of `keyB` succeeded, the decoupled `processWaitingCreationRequests` invocation shall then handle the 2nd `keyB` request first, before the 90 `keyA` requests.

Comment (sophokles73) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:71]: I see

File: clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (sophokles73) [reply clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java:95]: I see

**Review by sophokles73 — APPROVED** [review]
LGTM
