### PR TITLE
[#3136] Preserve RoutingContext error status code

### LINKED ISSUE #3136: HTTP request with invalid 'origin' header is causing status 500 response (not 403)
When a client sends an HTTP request with an invalid `origin` header to the HTTP adapter or to the device registry, the response will contain status code 500 instead of 403.

Log output:
```
HTTP2022-03-03 18:08:53,529 DEBUG [org.ecl.hon.ser.htt.DefaultFailureHandler] (vert.x-eventloop-thread-1) handling failed route for request [method: OPTIONS, URI: http://127.0.0.1.nip.io:49340/telemetry, status: 403] - null: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
HTTP2022-03-03 18:08:53,532 DEBUG [org.ecl.hon.ser.htt.DefaultFailureHandler] (vert.x-eventloop-thread-1) unexpected internal failure: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
HTTP2022-03-03 18:08:53,546 TRACE [org.ecl.hon.ser.htt.ComponentMetaDataDecorator] (vert.x-eventloop-thread-1) logging failed processing of request
HTTP2022-03-03 18:08:53,547 WARN  [org.ecl.hon.tra.TracingHelper] (vert.x-eventloop-thread-1) An unexpected error occurred! [logged on span [8c7b43caea8b1942:8c7b43caea8b1942:0:1 - OPTIONS]]: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
```
The Hono `DefaultFailureHandler` ignores the already set context status code 403 here and sets status 500.

### PR DESCRIPTION
**Pull request by calohmn**
Also prevent `WARN` log entries on HTTP client errors.

This fixes #3136.

### CODE REVIEW

File: core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java [hunk 1]
```diff
@@ -181,7 +181,24 @@ public static void setDeviceTags(final Span span, final String tenantId, final S
...
+
+    /**
+     * Marks an <em>OpenTracing</em> span as erroneous and logs an exception.
+     * <p>
+     * This method does <em>not</em> finish the span.
+     *
+     * @param span The span to mark.
+     * @param error The exception that has occurred.
+     * @param skipUnexpectedErrorCheck Whether to skip the check for an unexpected error, meaning no WARN log entry will
+     *            be created for such an error.
```
Comment (sophokles73) [inline core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java:195]: FMPOV the *logError(Span, Throwable)* method's default behavior (of passing in `false`) should be documented in its JavaDoc.

File: service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java [hunk 2]
```diff
@@ -71,6 +72,8 @@ public void handle(final RoutingContext ctx) {
                     } else if (ctx.failure() instanceof HttpException) {
                         final HttpException e = (HttpException) ctx.failure();
                         sendError(ctx.response(), e.getStatusCode(), e.getMessage());
+                    } else if (ctx.statusCode() >= 400 && ctx.statusCode() < 600) {
+                        sendError(ctx.response(), ctx.statusCode(), ctx.failure().getMessage());
```
Comment (sophokles73) [inline service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java:76]: IMHO we should not put the exception's detail message into the response body. Otherwise we might expose details regarding the internal implementation to clients/attackers. For the same reason we should probably also change the code for handling *ServiceInvocationException*s above and use `ServiceInvocationException.getClientFacingMessage()` instead?

Comment (calohmn) [reply service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java]: Sticking to the methods available in the `ServiceInvocationException` class, we could use 
`ServiceInvocationException.getErrorMessageForExternalClient(ctx.failure())`
here.
This however would only override the `ctx.failure().getMessage()` message in case a `ServerErrorException` was thrown.
For the conditional block added above, this would make no difference.

The `getErrorMessageForExternalClient` method originated from the code that assembled the error message for AMQP adapter responses:
https://github.com/eclipse/hono/pull/2499/files#diff-5af44e2d2a3f6823bd0dfa0304a475f621149fe320d4f57923b08ad10626cf14R1290

It is now used in the CoAP and MQTT adapters as well.
I would adapt that method in a separate PR.

I've adapted the last commit here to use `getErrorMessageForExternalClient` in the `DefaultFailureHandler` now.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Comment by calohmn** [comment]
The error message change here has caused integration test errors:
```
Error:    TelemetryHttpIT.testUploadMessageFailsForNoConsumer value of: getString(...)
expected: no consumer available
but was : Temporarily unavailable

Error:    TelemetryHttpIT.testUploadQos1MessageFailsIfDeliveryStateNotUpdated value of: getString(...)
expected: consumer failed to indicate in time whether it has processed the message
but was : Temporarily unavailable
```
Always taking the `ServerErrorException` client-facing error message requires further changes to the `HttpUtils#serviceUnavailable()` method, where a `ServerErrorException` gets created with a message that is supposed to be client-facing.

So, I've changed this PR back to always using the exception message like before, sticking to the status code fix here.

**Comment by sophokles73** [comment]
@calohmn is there anything you need from me?

**Comment by calohmn** [comment]
No, merging it.
