### PR TITLE
Fix #104: Do not register drain handlers in protocol adapters

### LINKED ISSUE #104: Protocol adapters should reject messages when no credit is available
Currently, the REST and MQTT adapter both register drain handlers when they do not have enough credit to forward a message from a client. This way, the message gets forwarded as soon as the Hono server provides the adapter with some credit. We had introduced this behavior in order to prevent a somewhat odd behavior when the adapter is started up from scratch and has no link to Hono for sending e.g. telemetry data open yet.
The link creation will be triggered with the first message being uploaded to the adapter from a client. However, at that point the link has no credit yet (because it has been just opened) and so cannot immediately forward the message to the Hono server. The adpter has two options: rejecting the message from the client based on the fact that the adapter currently has no credit or (and this is what we have implemented) register a drain handler which gets notified as soon as credit is available and then sends the message to the server.

While this currently prevents the client from receiving an annoying error message when trying to send its first message, this also has some drawbacks:
1. When another request to upload a message is issued by another client and the adapter has not yet received credit, the second client gets an error (the REST adapter will return a 500 HTTP status code) and thus experiences different behavior than the first one.
2. Once the adapter gets some credit, the registered drain handler will be called back and the original message will be forwarded. However, this message might very well be quite old by the time the credit is received and there may have been multiple requests by the client in the meantime for uploading data which all will have failed. This way, we prioritize an old message over (potentially multiple) newer ones.
3. Clients (message senders) need to be prepared to handle the case where the protocol adapter has no credits (anymore) in any case. In the end, that's the whole purpose of using a protocol like AMQP which supports backpressure being pshed back to the client. Consequently, we should be able to rely on the fact that clients can handle a message being rejected by the adapter.

I therefore think that we should change the default behavior of our protocol adapters so that they *always* reject messages if they do not have credit, regardless of whether this is because the link to Hono has just been established or because the Hono server has *drained* the adapter. This way we get a consistent behavior throughout the system, even if this comes with a little inconvenience in the special case where the adapter has just been started up.

### PR DESCRIPTION
**Pull request by sophokles73**
As already discussed in #104 this PR updates the REST and MQTT adapters to no longer register a drain handler in case no credits are available. Instead, the client's request is rejected (REST adapter) or the connection closed (MQTT adapter).

### CODE REVIEW

File: adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java [hunk 1]
```diff
@@ -162,8 +169,12 @@ private void handleEndpointConnection(final MqttEndpoint endpoint) {
             endpoint.reject(MqttConnectReturnCode.CONNECTION_REFUSED_SERVER_UNAVAILABLE);
 
         } else {
-
-            endpoint.publishHandler(message -> {
+            final AtomicBoolean clientConnected = new AtomicBoolean(false);
```
Comment (ppatierno) [inline adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java]: The MqttEndpoint has the client state (connected or not) but it's not exposed through the interface. I can expose it now making available to you. if you want you can merge this change and then I'll update with the new property from the MqttEndpoint.

Comment (sophokles73) [inline adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java]: I think that would be best, in particular because we would not see it being exposed on the interface before 3.4.0. FINAL, I guess ...

Comment (ppatierno) [inline adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java]: The Vert.x 3.4.0 is already out. I exposed isConnected in the current master branch for the mqtt server. I think we have to wait for the 3.4.1 that could be not so far.
